### ISSUE TITLE
 No public key: Key with id:

### ISSUE THREAD

**Issue by ismai117** [KevinnZou/compose-multiplatform-library-template#3]
Gradle failed with repeated lines -   No public key: Key with id: (xxxxxxxxxxxxx) was not able to be located on ...

**Comment by KevinnZou** [comment]
@ismai117 Thanks for your feedback! I am wondering which gradle tasks are you running, or just syncing.

**Comment by ismai117** [comment]
its sorted now, I just had to upload my public GPG key to the keyserver.

I appreciate your work on the library template!, I've finally released my first ever library which you can check out on my repo. it's called Kottie. thanks for the help!!

**Comment by KevinnZou** [comment]
@ismai117 Great job!

**Comment by ismai117** [comment]
hi @KevinnZou, I just released a new version "1.1.0", it  was successful but when I search the dependency in nexus repo manager. it hasn't updated for all targets 

![Screenshot 2024-01-07 at 01 48 47](https://github.com/KevinnZou/compose-multiplatform-library-template/assets/88812838/2ed6b9fc-fe35-489c-928c-efe8917a4913)

**Comment by KevinnZou** [comment]
@ismai117 It seems that `kottie-android` has version 1.1.0. Did you publish all the artifacts?

**Comment by ismai117** [comment]
![Screenshot 2024-01-07 at 01 57 08](https://github.com/KevinnZou/compose-multiplatform-library-template/assets/88812838/155e3c2e-9940-4002-84a4-e8e68c15aae7)
this is what I have in the configuration. I'm not 100% sure. 

I followed the instruction like the first release which worked

 "Automatic release[¶](https://vanniktech.github.io/gradle-maven-publish-plugin/central/#automatic-release)

Run the following task to let the plugin handle all steps automatically:

./gradlew publishAndReleaseToMavenCentral --no-configuration-cache",

 I tried this again but this time it hasn't updated all targets

**Comment by KevinnZou** [comment]
@ismai117 You should run publishAllPublicationsToMaven*.

**Comment by ismai117** [comment]
I've tried that but for some reason its not releasing the new version which is odd

**Comment by ismai117** [comment]
It's working now. I used publishAllPublicationsToMaven, but I had to change the version to 1.2.0. thanks for the help!!

**Comment by ismai117** [comment]
Hi @KevinnZou,  I'm trying to use 2 libraries together which I created and pushed to maven using your template. 

Deps

 implementation("io.github.ismai117:kottie:1.4.1")
 implementation("io.github.ismai117:KSend:1.0.1")

Error Message 

Duplicate class GetPlatformNameKt found in modules jetified-lib-release-runtime (io.github.ismai117:KSend-android:1.0.1) and jetified-lib-release-runtime (io.github.ismai117:kottie-android:1.4.1)

**Comment by KevinnZou** [comment]
Hi @ismai117, I encountered that issue in my project before and it turned out to be the problem with the Kotlin Multiplatform plugin. It does not allow the same class name for different modules. However, I believe this issue has been fixed and it is now working well for me.

One difference is that you are encountering the problem after importing two libraries. This issue should not occur unless the two libraries have the same package name. If that is the case, try to differentiate them by renaming one of the packages.

Please note that this template only defines the project structure and applies necessary plugins. It does not perform any additional tasks. Therefore, it should not be the primary cause of any errors.

**Comment by ismai117** [comment]
its fixed now, the error occurred because both libraries had the same filename "getPlatformName.kt"

one last question, if I rename the artifactid, will it replace the other versions on maven? 

from: coordinates("io.github.ismai117", "KSend", "1.0.2")
to:  coordinates("io.github.ismai117", "ksend", "1.0.3")

**Comment by KevinnZou** [comment]
@ismai117 No, it will only take effect from the current version.
